#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

if [ -z "${GOPATH:-}" ]; then
  # workaround. can be dropped after revendoring gardener/gardener
  mkdir -p $HOME/go
  export GOPATH=$HOME/go
fi

make verify
