apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-traffic-gauger
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-traffic-gauger
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-traffic-gauger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-traffic-gauger
subjects:
  - kind: ServiceAccount
    name: network-traffic-gauger
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-traffic-gauger
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: network-traffic-gauger
  template:
    metadata:
      labels:
        app: network-traffic-gauger
    spec:
      serviceAccountName: network-traffic-gauger
      hostNetwork: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: setup
          image: europe-docker.pkg.dev/gardener-project/snapshots/gardener/network-traffic-gauger:dev
          imagePullPolicy: Never
          command: ["/net-gauger", "setup", "--enable-accounting"]
          securityContext:
            privileged: true
      containers:
        - name: agent
          image: europe-docker.pkg.dev/gardener-project/snapshots/gardener/network-traffic-gauger:dev
          imagePullPolicy: Never
          command:
            - /net-gauger
            - run-agent
            - --metrics-port=16160
            - --dump-period=30s
            - --extract-local-ranges-from-kubernetes
            - --node-name=$(NODE_NAME)
            - --cluster-ranges=10.244.0.0/16
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 16160
              name: metrics
              protocol: TCP
          securityContext:
            privileged: true
